fixing the stateful-set

diff --git a/manifests/jumpstarter-qemu/stateful-set.yaml b/manifests/jumpstarter-qemu/stateful-set.yaml
--- a/manifests/jumpstarter-qemu/stateful-set.yaml
+++ b/manifests/jumpstarter-qemu/stateful-set.yaml
@@ -62,10 +62,6 @@ spec:
         - name: registry-ca
           configMap:
             name: registry-service-ca
-        #- name: tpm
-        #  hostPath:
-        #    path: /dev/tpmrm0
-        #    type: CharDevice
 
       initContainers:
         - name: jumpstarter-init
@@ -130,8 +126,6 @@ spec:
               name: dev-kvm
             - mountPath: /dev/vhost-vsock
               name: dev-vhost-vsock
-            #- mountPath: /dev/tpmrm0
-            #  name: tpm
             - mountPath: /etc/pki/ca-trust/source/anchors/service-ca-bundle.crt
               name: registry-ca
               subPath: service-ca-bundle.crt
@@ -148,6 +142,28 @@ spec:
             - -c
             - |
               set -eo pipefail
+
+              # start software TPM
+              swtpm socket \
+                --tpmstate dir=/tmp/swtpm \
+                --tpm2 \
+                --ctrl type=tcp,port=2322 \
+                --server type=tcp,port=2321 \
+                --flags not-need-init &
+
+              export TPM2TOOLS_TCTI="swtpm:host=127.0.0.1,port=2321"
+
+              timeout=10
+              while ! nc -z 127.0.0.1 2321 2>/dev/null; do
+                sleep 0.1
+                timeout=$((timeout - 1))
+                if [ "$timeout" -le 0 ]; then
+                  echo "ERROR: swtpm failed to start" >&2
+                  exit 1
+                fi
+              done
+              tpm2_startup -c
+
               source /venv/bin/activate
 
               # update to latest jumpstarter version
